# ARG IMAGE_BASE_NAME
ARG IMAGE_BASE_NAME=wingrammer/kauza
ARG BASE_IMAGE_HASH

FROM ${IMAGE_BASE_NAME}:base-${BASE_IMAGE_HASH}

ARG POETRY_VERSION

# install poetry
ENV POETRY_VERSION ${POETRY_VERSION}
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH "/root/.local/bin:${PATH}"
