name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive 
          token: ${{ secrets.KAUZA_DIALOG_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: wingrammer/kauza:13-06-2025-01
          build-args: |
            IMAGE_BASE_NAME=wingrammer/kauza
            BASE_IMAGE_HASH=latest
            BASE_BUILDER_IMAGE_HASH=latest-poetry-1.8.4